use button as form submit element
joeday/joedaymusic pull request #9
Opened 2024-12-09 17:53 UTC by buckrivard

2024-12-09 18:37 UTC, buckrivard commented on pages/index.js
> +const hideModal = () => localStorage.setItem(HIDE_SUBSCRIBER_MODAL_KEY, "true");
nope, this is to set the flag for 'hidden' state to true

2024-12-09 18:45 UTC, joeday requested changes
@buckrivard a few questions:

1. The modal is not revealing itself. I tested on multiple browsers in private windows. 
2. Can you update the `SubscribeForm.module.css` file so that the styles applied to the `input[type="submit"]` applies to the button?

2024-12-10 05:13 UTC, joeday commented
This is looking good to me. If you're done, I'm ready to merge it.

2024-12-16 19:45 UTC, joeday approved these changes
Looks good. Let's goooo

2024-12-16 19:45 UTC, merged